name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: depend
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libbz2-1.0 zlib1g 

    - name: make
      run: make -f makefile

    - name: check
      run: |
        ls -l
        ls -l bin
      
    - name: using zip for artifact
      run: |
        zip -r bin bin/

    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v3.1.2rc1
        release_name: v3.1.2rc1
        draft: false
        prerelease: false

    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin.zip
        asset_name: bin.zip
        asset_content_type: application/gzip

    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
